version: '3'

services:
  app:
    image: node:12
    container_name: app_ac
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
      - NODE_ENV=${APP_ENV}
      - VIRTUAL_HOST=${HOST_NAME}
      - LETSENCRYPT_HOST=${HOST_NAME}
      - LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets-encrypt
    restart: always
    depends_on:
      - "nginx-proxy"
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:5.7
    container_name: mysql_ac
    environment: 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306

volumes:
  certs:
  html:
  vhost:
  dhparam:
